### ISSUE TITLE
Update extensions for compatibility with newer exoplayer versions

### ISSUE THREAD

**Issue by saecki** [PaulWoitaschek/ExoPlayer-Extensions-Autobuild#2]
Exoplayer `2.13.x` introduced a playlist API that can't be used with the current extension version.
It would be nice if the flac extension-autobuild could be updated to be compatible with newer Exoplayer versions. The current version `2.11.4` is compatible to Exoplayer versions of `2.11.x`, but breaks with `2.12.x`.

**Comment by PaulWoitaschek** [comment]
Fell free to open a PR. This project is basically a fork of exoplayer so you can merge upstream and tag the commits without the `r` prefix for a release.

**Comment by saecki** [comment]
Thanks for the quick response. I'll give it a shot.
